title: Henrik Becker Consulting AB
#usp: Building the right software right
repository: handiman/handiman.github.io
production_url: https://www.henrikbecker.net
author:
  name: Henrik Becker
  github: handiman
#tile_color: '#303030'
permalink: pretty
sass:
 sass_dir: _sass
 style: compressed
sass:
 sass_dir: _sass
 style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-readme-index
#remote_theme: handiman/jekyll-theme-gnap  
#remote_theme: pages-themes/minimal@v0.2.0

exclude:  
 - node_modules
 - Gemfile
 - Gemfile.lock, 
 - "*.orig"

collections:
 usp:
  output: false
 projects:
  output: false
 employment:
  output: false
 certs:
  output: false 
 fun_facts:
  output: false

excerpt_separator: <!--more-->

defaults:
 - scope:
    path: ""
   values: 
    layout: default
 - scope:
    path: README.md
   values: 
    layout: cv
 - scope:
    path: googlef0bc3dbe928e1f73.html
   values:
    sitemap: false
 - scope:
    path: assets/**/*.*
   values:
    sitemap: false
 - scope:
    path: cv.html
   values:
    sitemap: false
 - scope:
    path: contact.html
   values:
    sitemap: false

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false    