name: Update Gist
on: 
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps: 
      - name: Update Gist
        shell: bash
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          ./.github/workflows/update-gist.sh $AUTH_TOKEN 3881a8e890dd1032cce3f5e655859717
