name: Update Gist
on: 
  workflow_dispatch:
  page_build: 
jobs:
  update:
    runs-on: ubuntu-latest
    steps: 
      - name: Update Gist
        run: |
          curl --output-file ./resume.json https://www.henrikbecker.net/assets/henrik-becker.json
          curl https://api.github.com/gists/171c100064ac9809bded620d2f3f230f -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer {{ secrets.AUTH_TOKEN }}" -d '{"description":"CI","files":{"resume.json":{"filename":"resume.json","content":"$(<resume.json)"}}}'
