name: Update Gist
on: 
  workflow_dispatch:
  page_build: 
jobs:
  update:
    runs-on: ubuntu-latest
    steps: 
      - name: Update Gist
        run: ./.github/workflows/update-gist.sh {{ secrets.OAUTH_TOKEN }} 171c100064ac9809bded620d2f3f230f
